core/urls.py
from django.urls import path
from .views import HomePageView, SamplePageView

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageView.as_view(), name="sample"),
]

pages/urls.py
from django.urls import path
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

urlpatterns = [
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:page_slug>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreate.as_view(), name='create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name='delete'),

] 

profiles/urls.py
from django.urls import path
from .views import ProfileListView, ProfileDetailView

urlpatterns = [
    path('', ProfileListView.as_view(), name='list_profile'),
    path('<str:username>/', ProfileDetailView.as_view(),name='detail')
]

registration/urls.py
from django.urls import path
from .views import SignupView, ProfileUpdate, EmailUpdate

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', ProfileUpdate.as_view(), name='profile'),
    path('profile/email/', EmailUpdate.as_view(), name='profile_email')
]

webplayground/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include(('pages.urls','pages'),namespace='pages')),
    path('',include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('profiles/', include(('profiles.urls','profiles'),namespace='profiles')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

messenger/models.py
from enum import auto
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed


# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

class Thread(models.Model):
    users = models.ManyToManyField(User, related_name='threads')
    messages = models.ManyToManyField(Message)


def messages_changed(sender, **kwargs):
    instance = kwargs.pop('instance', None)
    action = kwargs.pop('action', None)
    pk_set = kwargs.pop('pk_set', None)

    print(instance, action, pk_set)
    false_pk_set = set()
    if action is "pre_add":
        for msg_pk in pk_set:
            msg = Message.objects.get(pk=msg_pk)
            if msg.user not in instance.users.all():
                print("este es el falso {}".format(msg.user))
                false_pk_set.add(msg_pk)

    # Eliminamos los mensajes que estan pk_set que aparecen en false_pk_set
    pk_set.difference_update(false_pk_set)



m2m_changed.connect(messages_changed, sender=Thread.messages.through)

pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

profiles/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms
from .models import Page

class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ['title', 'content', 'order']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titulo'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Contenido'}),
            'order': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Orden'}),
        }
        labels = {
            'title': '',
            'content': '',
            'order': ''
        }

core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Mi web lala"
        return context


class SamplePageView(TemplateView):
    template_name = "core/sample.html"

messenger/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from .models import Page
from .forms import PageForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from django.urls import reverse_lazy, reverse

# Create your views here.

# Return List of instances of a model
# def pages(request):
#     pages = get_list_or_404(Page)
#     return render(request, 'pages/pages.html', {'pages':pages})
class StaffRequiredMIxin(object):
    """Este mixin requerira que el usuario sea miembo del staff"""

    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        # el decorador suplanta este codigo
        # manage request
        # if not request.user.is_staff:
        #     return redirect(reverse_lazy('admin:login'))
        return super(StaffRequiredMIxin,self).dispatch(request, *args, **kwargs)



class PageListView(ListView):
    model = Page

# Return an instance of a model
# def page(request, page_id, page_slug):
#     page = get_object_or_404(Page, id=page_id)
#     return render(request, 'pages/page.html', {'page':page})

class PageDetailView(DetailView):
    model = Page

@method_decorator(staff_member_required, name='dispatch')
class PageCreate(CreateView):
    model = Page
    form_class = PageForm
    success_url = reverse_lazy('pages:pages')

@method_decorator(staff_member_required, name='dispatch')
class PageUpdate(UpdateView):
    model = Page
    form_class = PageForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('pages:update', args=[self.object.id]) + '?ok'

@method_decorator(staff_member_required, name='dispatch')
class PageDelete(DeleteView):
    model = Page
    success_url = reverse_lazy('pages:pages')

profiles/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


from registration.models import Profile


# Create your views here.
class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    paginate_by = 3

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profiles/profile_detail.html'

    def get_object(self):
        return get_object_or_404(Profile, user__username=self.kwargs['username'])

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Playground</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:pages' %}">Páginas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:list_profile' %}">Perfiles</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile' %}">Perfil</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Acceder</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Registrarse</a>
                </li>
              {% endif %}
              
            </ul>
          </div>
        </div>
      </nav>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-top:50px; text-align:center;">
    <h1>Web Playground | {{title}} </h1>
    <p class="lead">CBV, autenticación, registros, perfiles y más</p>
  </div>
</div>
{% endblock %}

core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/includes/pages_menu.html
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<link href="{% static 'pages/css/custom_ckeditor.css' %}" rel="stylesheet">

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:create' %}"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}

pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar <b>"{{ object }}"</b>?</p>
                <input type="submit" class="btn btn-primary btn-block" value="Sí, borrar la página" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html' %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{page.title}}</h2>
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'pages:update' page.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
          <form action="" method="post">{% csrf_token %}
              {{ form.as_p }}
              <div class="text-center">
                <input type="submit" class="btn btn-primary btn-block" value="Crear página" />
              </div>
          </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

pages/templates/pages/page_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html' %}
<main role="main">
  <div class="container mb-4">
    {% for page in page_list %}
      <div class="row mt-3">
        <div class="col-md-9 mx-auto">
          <h2 class="mb-4">{{page.title}}</h2>
          <div>
            <p>{{page.content|striptags|safe|truncatechars:"200"}}</p>
            <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más</a>

              {% if request.user.is_staff %}
                | <a href="{% url 'pages:update' page.id %}">Editar</a>
                | <a href="{% url 'pages:delete' page.id %}">Borrar</a>
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}

pages/templates/pages/page_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <div>
            {% if 'ok' in request.GET %}
                <p style="color: green;">
                  Pagina Editada correctamente.
                  <a href="{% url 'pages:page' page.id page.title|slugify %}">Haz clic aqui para ver el resultado</a>
                </p>              
            {% endif %}
            <form action="" method="post">{% csrf_token %}
              {{ form.as_p }}
              <div class="text-center">
                <input type="submit" class="btn btn-primary btn-block" value="Actualizar página" />
              </div>
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

profiles/templates/profiles/includes/pagination.html
<!-- Menú de paginación -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&laquo;</a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      <li class="page-item {% if page_obj.number == i %}active{% endif %}">
        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item ">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">&raquo;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

profiles/templates/profiles/profile_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{profile.user}}{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row">
            <!-- Avatar -->
            <div class="col-md-2">
              {% if profile.avatar %}
                <img src="{{profile.avatar.url}}" class="img-fluid">
              {% else %}
                <img src="{% static 'registration/img/no-avatar.jpg' %}" class="img-fluid">
              {% endif %}
            </div>
            <!-- Campos -->
            <div class="col-md-10">
              <h3>{{profile.user}}</h3>
              {% if profile.bio %}<p>{{profile.bio}}</p>{% endif %}
              {% if profile.link %}<p><a href="{{profile.link}}" target="_blank">{{profile.link}}</a></p>{% endif %}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

profiles/templates/profiles/profile_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Perfiles{% endblock %}
{% block content %}
<style>.profile-avatar{float:left;width:4rem;height:4rem}.profile-data{padding-left:4.5rem;padding-top:.4rem;}</style>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <h2>Perfiles</h2>
        <div class="row">
          {% for profile in profile_list %}
            <div class="col-md-4 mt-2 mb-3 ">
              <div class="row p-1">
                <div class="col-md-12">
                  {% if profile.avatar %}
                    <img src="{{profile.avatar.url}}" class="img-fluid profile-avatar">
                  {% else %}
                    <img src="{% static 'registration/img/no-avatar.jpg' %}" class="img-fluid profile-avatar">
                  {% endif %}
                  <p class="profile-data">
                    <b>{{profile.user|truncatechars:"16"}}</b><br>
                    <a href="{% url 'profiles:detail' profile.user.username %}">Ver perfil</a>
                  </p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
        
        {% include 'profiles/includes/pagination.html'%}

      </div>
    </div>
  </div>
</main>
{% endblock %}